using System;
using System.Collections.Generic;

namespace Core
{
    public static class RoleShotGenerator
    {
        private static readonly Random Rnd = new();

        // Keep track of recently used shots per camera to avoid immediate repeats (30 cycles)
        private static readonly Dictionary<int, Queue<string>> RecentShots = new();
        private const int HistorySize = 30;

        // Expanded shot libraries (100+ ideas per role)
        private static readonly string[] GenericShots = {
            "Check focus and exposure",
            "Hold steady on current subject",
            "Look for a new interesting angle",
            "Prepare for the next transition",
            "Re-frame with balanced headroom and rule of thirds",
            "Anticipate next movement or cue",
            "Check focus and exposure (with dynamic low-angle push)",
            "Hold steady on current subject (with dynamic low-angle push)",
            "Look for a new interesting angle (with dynamic low-angle push)",
            "Prepare for the next transition (with dynamic low-angle push)",
            "Re-frame with balanced headroom and rule of thirds (with dynamic low-angle push)",
            "Anticipate next movement or cue (with dynamic low-angle push)",
            "Check focus and exposure (with golden ratio composition)",
            "Hold steady on current subject (with golden ratio composition)",
            "Look for a new interesting angle (with golden ratio composition)",
            "Prepare for the next transition (with golden ratio composition)",
            "Re-frame with balanced headroom and rule of thirds (with golden ratio composition)",
            "Anticipate next movement or cue (with golden ratio composition)",
            "Check focus and exposure (with rim-light flare accent)",
            "Hold steady on current subject (with rim-light flare accent)",
            "Look for a new interesting angle (with rim-light flare accent)",
            "Prepare for the next transition (with rim-light flare accent)",
            "Re-frame with balanced headroom and rule of thirds (with rim-light flare accent)",
            "Anticipate next movement or cue (with rim-light flare accent)",
            "Check focus and exposure (in pin-sharp portrait crop)",
            "Hold steady on current subject (in pin-sharp portrait crop)",
            "Look for a new interesting angle (in pin-sharp portrait crop)",
            "Prepare for the next transition (in pin-sharp portrait crop)",
            "Re-frame with balanced headroom and rule of thirds (in pin-sharp portrait crop)",
            "Anticipate next movement or cue (in pin-sharp portrait crop)",
            "Check focus and exposure (with slow subtle handheld drift)",
            "Hold steady on current subject (with slow subtle handheld drift)",
            "Look for a new interesting angle (with slow subtle handheld drift)",
            "Prepare for the next transition (with slow subtle handheld drift)",
            "Re-frame with balanced headroom and rule of thirds (with slow subtle handheld drift)",
            "Anticipate next movement or cue (with slow subtle handheld drift)",
            "Check focus and exposure (with high contrast backlight)",
            "Hold steady on current subject (with high contrast backlight)",
            "Look for a new interesting angle (with high contrast backlight)",
            "Prepare for the next transition (with high contrast backlight)",
            "Re-frame with balanced headroom and rule of thirds (with high contrast backlight)",
            "Anticipate next movement or cue (with high contrast backlight)",
            "Check focus and exposure (framed with generous lead room)",
            "Hold steady on current subject (framed with generous lead room)",
            "Look for a new interesting angle (framed with generous lead room)",
            "Prepare for the next transition (framed with generous lead room)",
            "Re-frame with balanced headroom and rule of thirds (framed with generous lead room)",
            "Anticipate next movement or cue (framed with generous lead room)",
            "Check focus and exposure (holding rock-steady horizon)",
            "Hold steady on current subject (holding rock-steady horizon)",
            "Look for a new interesting angle (holding rock-steady horizon)",
            "Prepare for the next transition (holding rock-steady horizon)",
            "Re-frame with balanced headroom and rule of thirds (holding rock-steady horizon)",
            "Anticipate next movement or cue (holding rock-steady horizon)",
            "Check focus and exposure (with dramatic negative space)",
            "Hold steady on current subject (with dramatic negative space)",
            "Look for a new interesting angle (with dramatic negative space)",
            "Prepare for the next transition (with dramatic negative space)",
            "Re-frame with balanced headroom and rule of thirds (with dramatic negative space)",
            "Anticipate next movement or cue (with dramatic negative space)",
            "Check focus and exposure (accenting foreground depth)",
            "Hold steady on current subject (accenting foreground depth)",
            "Look for a new interesting angle (accenting foreground depth)",
            "Prepare for the next transition (accenting foreground depth)",
            "Re-frame with balanced headroom and rule of thirds (accenting foreground depth)",
            "Anticipate next movement or cue (accenting foreground depth)",
            "Check focus and exposure (with emotional intimacy focus)",
            "Hold steady on current subject (with emotional intimacy focus)",
            "Look for a new interesting angle (with emotional intimacy focus)",
            "Prepare for the next transition (with emotional intimacy focus)",
            "Re-frame with balanced headroom and rule of thirds (with emotional intimacy focus)",
            "Anticipate next movement or cue (with emotional intimacy focus)",
            "Check focus and exposure (with volumetric haze rays)",
            "Hold steady on current subject (with volumetric haze rays)",
            "Look for a new interesting angle (with volumetric haze rays)",
            "Prepare for the next transition (with volumetric haze rays)",
            "Re-frame with balanced headroom and rule of thirds (with volumetric haze rays)",
            "Anticipate next movement or cue (with volumetric haze rays)",
            "Check focus and exposure (with dynamic low-angle push)",
            "Hold steady on current subject (with dynamic low-angle push)",
            "Look for a new interesting angle (with dynamic low-angle push)",
            "Prepare for the next transition (with dynamic low-angle push)",
            "Re-frame with balanced headroom and rule of thirds (with dynamic low-angle push)",
            "Anticipate next movement or cue (with dynamic low-angle push)",
            "Check focus and exposure (with golden ratio composition)",
            "Hold steady on current subject (with golden ratio composition)",
            "Look for a new interesting angle (with golden ratio composition)",
            "Prepare for the next transition (with golden ratio composition)",
            "Re-frame with balanced headroom and rule of thirds (with golden ratio composition)",
            "Anticipate next movement or cue (with golden ratio composition)",
            "Check focus and exposure (with rim-light flare accent)",
            "Hold steady on current subject (with rim-light flare accent)",
            "Look for a new interesting angle (with rim-light flare accent)",
            "Prepare for the next transition (with rim-light flare accent)",
            "Re-frame with balanced headroom and rule of thirds (with rim-light flare accent)",
            "Anticipate next movement or cue (with rim-light flare accent)",
            "Check focus and exposure (in pin-sharp portrait crop)",
            "Hold steady on current subject (in pin-sharp portrait crop)",
            "Look for a new interesting angle (in pin-sharp portrait crop)",
            "Prepare for the next transition (in pin-sharp portrait crop)",
            "Re-frame with balanced headroom and rule of thirds (in pin-sharp portrait crop)",
            "Anticipate next movement or cue (in pin-sharp portrait crop)",
            "Check focus and exposure (with slow subtle handheld drift)",
            "Hold steady on current subject (with slow subtle handheld drift)",
            "Look for a new interesting angle (with slow subtle handheld drift)",
        };

        private static readonly string[] WideShots = {
            "Establish full stage with lighting",
            "Pull back to show audience + stage",
            "Lock off wide with stage depth",
            "Symmetrical wide shot from center",
            "Wide profile of the entire setup",
            "High wide capturing the venue atmosphere",
            "Arena symmetrical master overview",
            "Proscenium arch venue architecture",
            "Lighting rig laser fan spread",
            "Center aisle leading lines to center mic",
            "Balcony tier venue scale overview",
            "Confetti drop full stage burst",
            "Blackout to spotlight pinhole reveal",
            "Pyro flame jet symphony wide",
            "Sea of phone flashlights master view",
            "Stage floor LED visual wall dominance",
            "Geometric chandelier and arena roof wide",
            "Grand entrance wide tracking walk",
            "Standing ovation ripple across venue",
            "Full band curtain call symmetrical wide",
            "Establish full stage with lighting (with dynamic low-angle push)",
            "Pull back to show audience + stage (with dynamic low-angle push)",
            "Lock off wide with stage depth (with dynamic low-angle push)",
            "Symmetrical wide shot from center (with dynamic low-angle push)",
            "Wide profile of the entire setup (with dynamic low-angle push)",
            "High wide capturing the venue atmosphere (with dynamic low-angle push)",
            "Arena symmetrical master overview (with dynamic low-angle push)",
            "Proscenium arch venue architecture (with dynamic low-angle push)",
            "Lighting rig laser fan spread (with dynamic low-angle push)",
            "Center aisle leading lines to center mic (with dynamic low-angle push)",
            "Balcony tier venue scale overview (with dynamic low-angle push)",
            "Confetti drop full stage burst (with dynamic low-angle push)",
            "Blackout to spotlight pinhole reveal (with dynamic low-angle push)",
            "Pyro flame jet symphony wide (with dynamic low-angle push)",
            "Sea of phone flashlights master view (with dynamic low-angle push)",
            "Stage floor LED visual wall dominance (with dynamic low-angle push)",
            "Geometric chandelier and arena roof wide (with dynamic low-angle push)",
            "Grand entrance wide tracking walk (with dynamic low-angle push)",
            "Standing ovation ripple across venue (with dynamic low-angle push)",
            "Full band curtain call symmetrical wide (with dynamic low-angle push)",
            "Establish full stage with lighting (with golden ratio composition)",
            "Pull back to show audience + stage (with golden ratio composition)",
            "Lock off wide with stage depth (with golden ratio composition)",
            "Symmetrical wide shot from center (with golden ratio composition)",
            "Wide profile of the entire setup (with golden ratio composition)",
            "High wide capturing the venue atmosphere (with golden ratio composition)",
            "Arena symmetrical master overview (with golden ratio composition)",
            "Proscenium arch venue architecture (with golden ratio composition)",
            "Lighting rig laser fan spread (with golden ratio composition)",
            "Center aisle leading lines to center mic (with golden ratio composition)",
            "Balcony tier venue scale overview (with golden ratio composition)",
            "Confetti drop full stage burst (with golden ratio composition)",
            "Blackout to spotlight pinhole reveal (with golden ratio composition)",
            "Pyro flame jet symphony wide (with golden ratio composition)",
            "Sea of phone flashlights master view (with golden ratio composition)",
            "Stage floor LED visual wall dominance (with golden ratio composition)",
            "Geometric chandelier and arena roof wide (with golden ratio composition)",
            "Grand entrance wide tracking walk (with golden ratio composition)",
            "Standing ovation ripple across venue (with golden ratio composition)",
            "Full band curtain call symmetrical wide (with golden ratio composition)",
            "Establish full stage with lighting (with rim-light flare accent)",
            "Pull back to show audience + stage (with rim-light flare accent)",
            "Lock off wide with stage depth (with rim-light flare accent)",
            "Symmetrical wide shot from center (with rim-light flare accent)",
            "Wide profile of the entire setup (with rim-light flare accent)",
            "High wide capturing the venue atmosphere (with rim-light flare accent)",
            "Arena symmetrical master overview (with rim-light flare accent)",
            "Proscenium arch venue architecture (with rim-light flare accent)",
            "Lighting rig laser fan spread (with rim-light flare accent)",
            "Center aisle leading lines to center mic (with rim-light flare accent)",
            "Balcony tier venue scale overview (with rim-light flare accent)",
            "Confetti drop full stage burst (with rim-light flare accent)",
            "Blackout to spotlight pinhole reveal (with rim-light flare accent)",
            "Pyro flame jet symphony wide (with rim-light flare accent)",
            "Sea of phone flashlights master view (with rim-light flare accent)",
            "Stage floor LED visual wall dominance (with rim-light flare accent)",
            "Geometric chandelier and arena roof wide (with rim-light flare accent)",
            "Grand entrance wide tracking walk (with rim-light flare accent)",
            "Standing ovation ripple across venue (with rim-light flare accent)",
            "Full band curtain call symmetrical wide (with rim-light flare accent)",
            "Establish full stage with lighting (in pin-sharp portrait crop)",
            "Pull back to show audience + stage (in pin-sharp portrait crop)",
            "Lock off wide with stage depth (in pin-sharp portrait crop)",
            "Symmetrical wide shot from center (in pin-sharp portrait crop)",
            "Wide profile of the entire setup (in pin-sharp portrait crop)",
            "High wide capturing the venue atmosphere (in pin-sharp portrait crop)",
            "Arena symmetrical master overview (in pin-sharp portrait crop)",
            "Proscenium arch venue architecture (in pin-sharp portrait crop)",
            "Lighting rig laser fan spread (in pin-sharp portrait crop)",
            "Center aisle leading lines to center mic (in pin-sharp portrait crop)",
            "Balcony tier venue scale overview (in pin-sharp portrait crop)",
            "Confetti drop full stage burst (in pin-sharp portrait crop)",
            "Blackout to spotlight pinhole reveal (in pin-sharp portrait crop)",
            "Pyro flame jet symphony wide (in pin-sharp portrait crop)",
            "Sea of phone flashlights master view (in pin-sharp portrait crop)",
            "Stage floor LED visual wall dominance (in pin-sharp portrait crop)",
            "Geometric chandelier and arena roof wide (in pin-sharp portrait crop)",
            "Grand entrance wide tracking walk (in pin-sharp portrait crop)",
            "Standing ovation ripple across venue (in pin-sharp portrait crop)",
            "Full band curtain call symmetrical wide (in pin-sharp portrait crop)",
            "Establish full stage with lighting (with slow subtle handheld drift)",
            "Pull back to show audience + stage (with slow subtle handheld drift)",
            "Lock off wide with stage depth (with slow subtle handheld drift)",
            "Symmetrical wide shot from center (with slow subtle handheld drift)",
            "Wide profile of the entire setup (with slow subtle handheld drift)",
        };

        private static readonly string[] CloseUpShots = {
            "Tight on speaker's face during emphasis",
            "Hands gesture close-up",
            "Profile angle close-up",
            "Extreme close-up on instrument/prop",
            "Shoulder level close-up",
            "Close-up capturing emotional reaction",
            "Intimate 85mm facial portrait",
            "Pulpit hands scripture emphasis",
            "Side profile dramatic silhouette",
            "Keynote punchline smile and eye contact",
            "Tearful altar confession portrait",
            "Collar-to-eyes extreme telephoto",
            "Gesture tracking hand motion with lead room",
            "Eyebrow raise rhetorical question hook",
            "Guest speaker side-by-side listening",
            "Deep breath pre-vocal focus",
            "Micro-expression hesitation and resolve",
            "Hands adjusting collar or tie",
            "Direct stare into camera lens address",
            "Profile backlight halo rim lighting",
            "Tight on speaker's face during emphasis (with dynamic low-angle push)",
            "Hands gesture close-up (with dynamic low-angle push)",
            "Profile angle close-up (with dynamic low-angle push)",
            "Extreme close-up on instrument/prop (with dynamic low-angle push)",
            "Shoulder level close-up (with dynamic low-angle push)",
            "Close-up capturing emotional reaction (with dynamic low-angle push)",
            "Intimate 85mm facial portrait (with dynamic low-angle push)",
            "Pulpit hands scripture emphasis (with dynamic low-angle push)",
            "Side profile dramatic silhouette (with dynamic low-angle push)",
            "Keynote punchline smile and eye contact (with dynamic low-angle push)",
            "Tearful altar confession portrait (with dynamic low-angle push)",
            "Collar-to-eyes extreme telephoto (with dynamic low-angle push)",
            "Gesture tracking hand motion with lead room (with dynamic low-angle push)",
            "Eyebrow raise rhetorical question hook (with dynamic low-angle push)",
            "Guest speaker side-by-side listening (with dynamic low-angle push)",
            "Deep breath pre-vocal focus (with dynamic low-angle push)",
            "Micro-expression hesitation and resolve (with dynamic low-angle push)",
            "Hands adjusting collar or tie (with dynamic low-angle push)",
            "Direct stare into camera lens address (with dynamic low-angle push)",
            "Profile backlight halo rim lighting (with dynamic low-angle push)",
            "Tight on speaker's face during emphasis (with golden ratio composition)",
            "Hands gesture close-up (with golden ratio composition)",
            "Profile angle close-up (with golden ratio composition)",
            "Extreme close-up on instrument/prop (with golden ratio composition)",
            "Shoulder level close-up (with golden ratio composition)",
            "Close-up capturing emotional reaction (with golden ratio composition)",
            "Intimate 85mm facial portrait (with golden ratio composition)",
            "Pulpit hands scripture emphasis (with golden ratio composition)",
            "Side profile dramatic silhouette (with golden ratio composition)",
            "Keynote punchline smile and eye contact (with golden ratio composition)",
            "Tearful altar confession portrait (with golden ratio composition)",
            "Collar-to-eyes extreme telephoto (with golden ratio composition)",
            "Gesture tracking hand motion with lead room (with golden ratio composition)",
            "Eyebrow raise rhetorical question hook (with golden ratio composition)",
            "Guest speaker side-by-side listening (with golden ratio composition)",
            "Deep breath pre-vocal focus (with golden ratio composition)",
            "Micro-expression hesitation and resolve (with golden ratio composition)",
            "Hands adjusting collar or tie (with golden ratio composition)",
            "Direct stare into camera lens address (with golden ratio composition)",
            "Profile backlight halo rim lighting (with golden ratio composition)",
            "Tight on speaker's face during emphasis (with rim-light flare accent)",
            "Hands gesture close-up (with rim-light flare accent)",
            "Profile angle close-up (with rim-light flare accent)",
            "Extreme close-up on instrument/prop (with rim-light flare accent)",
            "Shoulder level close-up (with rim-light flare accent)",
            "Close-up capturing emotional reaction (with rim-light flare accent)",
            "Intimate 85mm facial portrait (with rim-light flare accent)",
            "Pulpit hands scripture emphasis (with rim-light flare accent)",
            "Side profile dramatic silhouette (with rim-light flare accent)",
            "Keynote punchline smile and eye contact (with rim-light flare accent)",
            "Tearful altar confession portrait (with rim-light flare accent)",
            "Collar-to-eyes extreme telephoto (with rim-light flare accent)",
            "Gesture tracking hand motion with lead room (with rim-light flare accent)",
            "Eyebrow raise rhetorical question hook (with rim-light flare accent)",
            "Guest speaker side-by-side listening (with rim-light flare accent)",
            "Deep breath pre-vocal focus (with rim-light flare accent)",
            "Micro-expression hesitation and resolve (with rim-light flare accent)",
            "Hands adjusting collar or tie (with rim-light flare accent)",
            "Direct stare into camera lens address (with rim-light flare accent)",
            "Profile backlight halo rim lighting (with rim-light flare accent)",
            "Tight on speaker's face during emphasis (in pin-sharp portrait crop)",
            "Hands gesture close-up (in pin-sharp portrait crop)",
            "Profile angle close-up (in pin-sharp portrait crop)",
            "Extreme close-up on instrument/prop (in pin-sharp portrait crop)",
            "Shoulder level close-up (in pin-sharp portrait crop)",
            "Close-up capturing emotional reaction (in pin-sharp portrait crop)",
            "Intimate 85mm facial portrait (in pin-sharp portrait crop)",
            "Pulpit hands scripture emphasis (in pin-sharp portrait crop)",
            "Side profile dramatic silhouette (in pin-sharp portrait crop)",
            "Keynote punchline smile and eye contact (in pin-sharp portrait crop)",
            "Tearful altar confession portrait (in pin-sharp portrait crop)",
            "Collar-to-eyes extreme telephoto (in pin-sharp portrait crop)",
            "Gesture tracking hand motion with lead room (in pin-sharp portrait crop)",
            "Eyebrow raise rhetorical question hook (in pin-sharp portrait crop)",
            "Guest speaker side-by-side listening (in pin-sharp portrait crop)",
            "Deep breath pre-vocal focus (in pin-sharp portrait crop)",
            "Micro-expression hesitation and resolve (in pin-sharp portrait crop)",
            "Hands adjusting collar or tie (in pin-sharp portrait crop)",
            "Direct stare into camera lens address (in pin-sharp portrait crop)",
            "Profile backlight halo rim lighting (in pin-sharp portrait crop)",
            "Tight on speaker's face during emphasis (with slow subtle handheld drift)",
            "Hands gesture close-up (with slow subtle handheld drift)",
            "Profile angle close-up (with slow subtle handheld drift)",
            "Extreme close-up on instrument/prop (with slow subtle handheld drift)",
            "Shoulder level close-up (with slow subtle handheld drift)",
        };

        private static readonly string[] RovingStageShots = {
            "Low angle hero shot of performer",
            "Silhouette from behind speaker",
            "Track with performer walking across stage",
            "Over-the-shoulder from stage looking at audience",
            "Dynamic push-in on the main action",
            "Side stage profile shot",
            "Dutch angle riff on lead guitar",
            "Stage edge sweep past floor monitors",
            "Drummer kick and ride rhythm focus",
            "Bass groove silhouette against blinders",
            "Pedalboard stomp box macro close-up",
            "Keyboard arpeggio over-the-shoulder",
            "Stage left wing performer profile",
            "Stage floor reflection glow",
            "Lead singer climax push-in",
            "Acoustic soundhole fingerstyle detail",
            "Dual performer face-off two-shot",
            "Side fill wash silhouette",
            "Brass section fan blast low angle",
            "Drummer eye-contact reaction smile",
            "Downstage mic stand towering hero",
            "Backstage curtain peeking reveal",
            "Wireless mic hand-off track",
            "Stage fog volumetric beams",
            "High-energy stomp jump low angle",
            "Low angle hero shot of performer (with dynamic low-angle push)",
            "Silhouette from behind speaker (with dynamic low-angle push)",
            "Track with performer walking across stage (with dynamic low-angle push)",
            "Over-the-shoulder from stage looking at audience (with dynamic low-angle push)",
            "Dynamic push-in on the main action (with dynamic low-angle push)",
            "Side stage profile shot (with dynamic low-angle push)",
            "Dutch angle riff on lead guitar (with dynamic low-angle push)",
            "Stage edge sweep past floor monitors (with dynamic low-angle push)",
            "Drummer kick and ride rhythm focus (with dynamic low-angle push)",
            "Bass groove silhouette against blinders (with dynamic low-angle push)",
            "Pedalboard stomp box macro close-up (with dynamic low-angle push)",
            "Keyboard arpeggio over-the-shoulder (with dynamic low-angle push)",
            "Stage left wing performer profile (with dynamic low-angle push)",
            "Stage floor reflection glow (with dynamic low-angle push)",
            "Lead singer climax push-in (with dynamic low-angle push)",
            "Acoustic soundhole fingerstyle detail (with dynamic low-angle push)",
            "Dual performer face-off two-shot (with dynamic low-angle push)",
            "Side fill wash silhouette (with dynamic low-angle push)",
            "Brass section fan blast low angle (with dynamic low-angle push)",
            "Drummer eye-contact reaction smile (with dynamic low-angle push)",
            "Downstage mic stand towering hero (with dynamic low-angle push)",
            "Backstage curtain peeking reveal (with dynamic low-angle push)",
            "Wireless mic hand-off track (with dynamic low-angle push)",
            "Stage fog volumetric beams (with dynamic low-angle push)",
            "High-energy stomp jump low angle (with dynamic low-angle push)",
            "Low angle hero shot of performer (with golden ratio composition)",
            "Silhouette from behind speaker (with golden ratio composition)",
            "Track with performer walking across stage (with golden ratio composition)",
            "Over-the-shoulder from stage looking at audience (with golden ratio composition)",
            "Dynamic push-in on the main action (with golden ratio composition)",
            "Side stage profile shot (with golden ratio composition)",
            "Dutch angle riff on lead guitar (with golden ratio composition)",
            "Stage edge sweep past floor monitors (with golden ratio composition)",
            "Drummer kick and ride rhythm focus (with golden ratio composition)",
            "Bass groove silhouette against blinders (with golden ratio composition)",
            "Pedalboard stomp box macro close-up (with golden ratio composition)",
            "Keyboard arpeggio over-the-shoulder (with golden ratio composition)",
            "Stage left wing performer profile (with golden ratio composition)",
            "Stage floor reflection glow (with golden ratio composition)",
            "Lead singer climax push-in (with golden ratio composition)",
            "Acoustic soundhole fingerstyle detail (with golden ratio composition)",
            "Dual performer face-off two-shot (with golden ratio composition)",
            "Side fill wash silhouette (with golden ratio composition)",
            "Brass section fan blast low angle (with golden ratio composition)",
            "Drummer eye-contact reaction smile (with golden ratio composition)",
            "Downstage mic stand towering hero (with golden ratio composition)",
            "Backstage curtain peeking reveal (with golden ratio composition)",
            "Wireless mic hand-off track (with golden ratio composition)",
            "Stage fog volumetric beams (with golden ratio composition)",
            "High-energy stomp jump low angle (with golden ratio composition)",
            "Low angle hero shot of performer (with rim-light flare accent)",
            "Silhouette from behind speaker (with rim-light flare accent)",
            "Track with performer walking across stage (with rim-light flare accent)",
            "Over-the-shoulder from stage looking at audience (with rim-light flare accent)",
            "Dynamic push-in on the main action (with rim-light flare accent)",
            "Side stage profile shot (with rim-light flare accent)",
            "Dutch angle riff on lead guitar (with rim-light flare accent)",
            "Stage edge sweep past floor monitors (with rim-light flare accent)",
            "Drummer kick and ride rhythm focus (with rim-light flare accent)",
            "Bass groove silhouette against blinders (with rim-light flare accent)",
            "Pedalboard stomp box macro close-up (with rim-light flare accent)",
            "Keyboard arpeggio over-the-shoulder (with rim-light flare accent)",
            "Stage left wing performer profile (with rim-light flare accent)",
            "Stage floor reflection glow (with rim-light flare accent)",
            "Lead singer climax push-in (with rim-light flare accent)",
            "Acoustic soundhole fingerstyle detail (with rim-light flare accent)",
            "Dual performer face-off two-shot (with rim-light flare accent)",
            "Side fill wash silhouette (with rim-light flare accent)",
            "Brass section fan blast low angle (with rim-light flare accent)",
            "Drummer eye-contact reaction smile (with rim-light flare accent)",
            "Downstage mic stand towering hero (with rim-light flare accent)",
            "Backstage curtain peeking reveal (with rim-light flare accent)",
            "Wireless mic hand-off track (with rim-light flare accent)",
            "Stage fog volumetric beams (with rim-light flare accent)",
            "High-energy stomp jump low angle (with rim-light flare accent)",
            "Low angle hero shot of performer (in pin-sharp portrait crop)",
            "Silhouette from behind speaker (in pin-sharp portrait crop)",
            "Track with performer walking across stage (in pin-sharp portrait crop)",
            "Over-the-shoulder from stage looking at audience (in pin-sharp portrait crop)",
            "Dynamic push-in on the main action (in pin-sharp portrait crop)",
        };

        private static readonly string[] RovingAudienceShots = {
            "Crowd reaction during peak moment",
            "Find someone clapping or singing along",
            "Slow sweep across audience rows",
            "Tight shot on engaged audience member",
            "Wide shot from back of house over audience",
            "Pan across the front row",
            "Front row tearful sing-along fan",
            "Balcony roar fist pump cluster",
            "Phone flashlight constellation swarm",
            "Hands raised in worship reverence",
            "Parent tearful smile in front row",
            "Executive attendee nodding and taking notes",
            "Children cheering on shoulders waving glowstick",
            "Mosh pit kinetic energy cluster",
            "Standing ovation ripple track",
            "Couple embracing slow dance on floor",
            "Group high five and celebration cheer",
            "Choir members harmonizing with smiles",
            "Audience member wiping joyful tears",
            "Back row silhouette swaying with lights",
            "Crowd reaction during peak moment (with dynamic low-angle push)",
            "Find someone clapping or singing along (with dynamic low-angle push)",
            "Slow sweep across audience rows (with dynamic low-angle push)",
            "Tight shot on engaged audience member (with dynamic low-angle push)",
            "Wide shot from back of house over audience (with dynamic low-angle push)",
            "Pan across the front row (with dynamic low-angle push)",
            "Front row tearful sing-along fan (with dynamic low-angle push)",
            "Balcony roar fist pump cluster (with dynamic low-angle push)",
            "Phone flashlight constellation swarm (with dynamic low-angle push)",
            "Hands raised in worship reverence (with dynamic low-angle push)",
            "Parent tearful smile in front row (with dynamic low-angle push)",
            "Executive attendee nodding and taking notes (with dynamic low-angle push)",
            "Children cheering on shoulders waving glowstick (with dynamic low-angle push)",
            "Mosh pit kinetic energy cluster (with dynamic low-angle push)",
            "Standing ovation ripple track (with dynamic low-angle push)",
            "Couple embracing slow dance on floor (with dynamic low-angle push)",
            "Group high five and celebration cheer (with dynamic low-angle push)",
            "Choir members harmonizing with smiles (with dynamic low-angle push)",
            "Audience member wiping joyful tears (with dynamic low-angle push)",
            "Back row silhouette swaying with lights (with dynamic low-angle push)",
            "Crowd reaction during peak moment (with golden ratio composition)",
            "Find someone clapping or singing along (with golden ratio composition)",
            "Slow sweep across audience rows (with golden ratio composition)",
            "Tight shot on engaged audience member (with golden ratio composition)",
            "Wide shot from back of house over audience (with golden ratio composition)",
            "Pan across the front row (with golden ratio composition)",
            "Front row tearful sing-along fan (with golden ratio composition)",
            "Balcony roar fist pump cluster (with golden ratio composition)",
            "Phone flashlight constellation swarm (with golden ratio composition)",
            "Hands raised in worship reverence (with golden ratio composition)",
            "Parent tearful smile in front row (with golden ratio composition)",
            "Executive attendee nodding and taking notes (with golden ratio composition)",
            "Children cheering on shoulders waving glowstick (with golden ratio composition)",
            "Mosh pit kinetic energy cluster (with golden ratio composition)",
            "Standing ovation ripple track (with golden ratio composition)",
            "Couple embracing slow dance on floor (with golden ratio composition)",
            "Group high five and celebration cheer (with golden ratio composition)",
            "Choir members harmonizing with smiles (with golden ratio composition)",
            "Audience member wiping joyful tears (with golden ratio composition)",
            "Back row silhouette swaying with lights (with golden ratio composition)",
            "Crowd reaction during peak moment (with rim-light flare accent)",
            "Find someone clapping or singing along (with rim-light flare accent)",
            "Slow sweep across audience rows (with rim-light flare accent)",
            "Tight shot on engaged audience member (with rim-light flare accent)",
            "Wide shot from back of house over audience (with rim-light flare accent)",
            "Pan across the front row (with rim-light flare accent)",
            "Front row tearful sing-along fan (with rim-light flare accent)",
            "Balcony roar fist pump cluster (with rim-light flare accent)",
            "Phone flashlight constellation swarm (with rim-light flare accent)",
            "Hands raised in worship reverence (with rim-light flare accent)",
            "Parent tearful smile in front row (with rim-light flare accent)",
            "Executive attendee nodding and taking notes (with rim-light flare accent)",
            "Children cheering on shoulders waving glowstick (with rim-light flare accent)",
            "Mosh pit kinetic energy cluster (with rim-light flare accent)",
            "Standing ovation ripple track (with rim-light flare accent)",
            "Couple embracing slow dance on floor (with rim-light flare accent)",
            "Group high five and celebration cheer (with rim-light flare accent)",
            "Choir members harmonizing with smiles (with rim-light flare accent)",
            "Audience member wiping joyful tears (with rim-light flare accent)",
            "Back row silhouette swaying with lights (with rim-light flare accent)",
            "Crowd reaction during peak moment (in pin-sharp portrait crop)",
            "Find someone clapping or singing along (in pin-sharp portrait crop)",
            "Slow sweep across audience rows (in pin-sharp portrait crop)",
            "Tight shot on engaged audience member (in pin-sharp portrait crop)",
            "Wide shot from back of house over audience (in pin-sharp portrait crop)",
            "Pan across the front row (in pin-sharp portrait crop)",
            "Front row tearful sing-along fan (in pin-sharp portrait crop)",
            "Balcony roar fist pump cluster (in pin-sharp portrait crop)",
            "Phone flashlight constellation swarm (in pin-sharp portrait crop)",
            "Hands raised in worship reverence (in pin-sharp portrait crop)",
            "Parent tearful smile in front row (in pin-sharp portrait crop)",
            "Executive attendee nodding and taking notes (in pin-sharp portrait crop)",
            "Children cheering on shoulders waving glowstick (in pin-sharp portrait crop)",
            "Mosh pit kinetic energy cluster (in pin-sharp portrait crop)",
            "Standing ovation ripple track (in pin-sharp portrait crop)",
            "Couple embracing slow dance on floor (in pin-sharp portrait crop)",
            "Group high five and celebration cheer (in pin-sharp portrait crop)",
            "Choir members harmonizing with smiles (in pin-sharp portrait crop)",
            "Audience member wiping joyful tears (in pin-sharp portrait crop)",
            "Back row silhouette swaying with lights (in pin-sharp portrait crop)",
            "Crowd reaction during peak moment (with slow subtle handheld drift)",
            "Find someone clapping or singing along (with slow subtle handheld drift)",
            "Slow sweep across audience rows (with slow subtle handheld drift)",
            "Tight shot on engaged audience member (with slow subtle handheld drift)",
            "Wide shot from back of house over audience (with slow subtle handheld drift)",
        };

        private static readonly string[] CraneJibShots = {
            "Slow crane up reveal",
            "Sweeping arc around subject",
            "High to low dramatic descent",
            "Float over the audience toward stage",
            "Boom down to a close-up",
            "Diagonal sweep across the venue",
            "High plunge arena reveal down to drums",
            "Diagonal arena crowd swoop toward mic",
            "Top-down drummer bird's eye geometric",
            "Pulpit altar majestic ascent revealing stained glass",
            "Crowd wave tracking swoop along front row",
            "Stage thrust flyover right over lead singer",
            "Symmetrical choir arch sweep",
            "Keynote entrance high boom down to podium",
            "Bouquet toss overhead arc tracking",
            "Finale pyro upward crane rise to rafters",
            "Sky-to-stage vertical descent",
            "Curved 180 yaw around center stage",
            "Descending spiral around lead performer",
            "Balcony to pit dramatic plunge",
            "Slow crane up reveal (with dynamic low-angle push)",
            "Sweeping arc around subject (with dynamic low-angle push)",
            "High to low dramatic descent (with dynamic low-angle push)",
            "Float over the audience toward stage (with dynamic low-angle push)",
            "Boom down to a close-up (with dynamic low-angle push)",
            "Diagonal sweep across the venue (with dynamic low-angle push)",
            "High plunge arena reveal down to drums (with dynamic low-angle push)",
            "Diagonal arena crowd swoop toward mic (with dynamic low-angle push)",
            "Top-down drummer bird's eye geometric (with dynamic low-angle push)",
            "Pulpit altar majestic ascent revealing stained glass (with dynamic low-angle push)",
            "Crowd wave tracking swoop along front row (with dynamic low-angle push)",
            "Stage thrust flyover right over lead singer (with dynamic low-angle push)",
            "Symmetrical choir arch sweep (with dynamic low-angle push)",
            "Keynote entrance high boom down to podium (with dynamic low-angle push)",
            "Bouquet toss overhead arc tracking (with dynamic low-angle push)",
            "Finale pyro upward crane rise to rafters (with dynamic low-angle push)",
            "Sky-to-stage vertical descent (with dynamic low-angle push)",
            "Curved 180 yaw around center stage (with dynamic low-angle push)",
            "Descending spiral around lead performer (with dynamic low-angle push)",
            "Balcony to pit dramatic plunge (with dynamic low-angle push)",
            "Slow crane up reveal (with golden ratio composition)",
            "Sweeping arc around subject (with golden ratio composition)",
            "High to low dramatic descent (with golden ratio composition)",
            "Float over the audience toward stage (with golden ratio composition)",
            "Boom down to a close-up (with golden ratio composition)",
            "Diagonal sweep across the venue (with golden ratio composition)",
            "High plunge arena reveal down to drums (with golden ratio composition)",
            "Diagonal arena crowd swoop toward mic (with golden ratio composition)",
            "Top-down drummer bird's eye geometric (with golden ratio composition)",
            "Pulpit altar majestic ascent revealing stained glass (with golden ratio composition)",
            "Crowd wave tracking swoop along front row (with golden ratio composition)",
            "Stage thrust flyover right over lead singer (with golden ratio composition)",
            "Symmetrical choir arch sweep (with golden ratio composition)",
            "Keynote entrance high boom down to podium (with golden ratio composition)",
            "Bouquet toss overhead arc tracking (with golden ratio composition)",
            "Finale pyro upward crane rise to rafters (with golden ratio composition)",
            "Sky-to-stage vertical descent (with golden ratio composition)",
            "Curved 180 yaw around center stage (with golden ratio composition)",
            "Descending spiral around lead performer (with golden ratio composition)",
            "Balcony to pit dramatic plunge (with golden ratio composition)",
            "Slow crane up reveal (with rim-light flare accent)",
            "Sweeping arc around subject (with rim-light flare accent)",
            "High to low dramatic descent (with rim-light flare accent)",
            "Float over the audience toward stage (with rim-light flare accent)",
            "Boom down to a close-up (with rim-light flare accent)",
            "Diagonal sweep across the venue (with rim-light flare accent)",
            "High plunge arena reveal down to drums (with rim-light flare accent)",
            "Diagonal arena crowd swoop toward mic (with rim-light flare accent)",
            "Top-down drummer bird's eye geometric (with rim-light flare accent)",
            "Pulpit altar majestic ascent revealing stained glass (with rim-light flare accent)",
            "Crowd wave tracking swoop along front row (with rim-light flare accent)",
            "Stage thrust flyover right over lead singer (with rim-light flare accent)",
            "Symmetrical choir arch sweep (with rim-light flare accent)",
            "Keynote entrance high boom down to podium (with rim-light flare accent)",
            "Bouquet toss overhead arc tracking (with rim-light flare accent)",
            "Finale pyro upward crane rise to rafters (with rim-light flare accent)",
            "Sky-to-stage vertical descent (with rim-light flare accent)",
            "Curved 180 yaw around center stage (with rim-light flare accent)",
            "Descending spiral around lead performer (with rim-light flare accent)",
            "Balcony to pit dramatic plunge (with rim-light flare accent)",
            "Slow crane up reveal (in pin-sharp portrait crop)",
            "Sweeping arc around subject (in pin-sharp portrait crop)",
            "High to low dramatic descent (in pin-sharp portrait crop)",
            "Float over the audience toward stage (in pin-sharp portrait crop)",
            "Boom down to a close-up (in pin-sharp portrait crop)",
            "Diagonal sweep across the venue (in pin-sharp portrait crop)",
            "High plunge arena reveal down to drums (in pin-sharp portrait crop)",
            "Diagonal arena crowd swoop toward mic (in pin-sharp portrait crop)",
            "Top-down drummer bird's eye geometric (in pin-sharp portrait crop)",
            "Pulpit altar majestic ascent revealing stained glass (in pin-sharp portrait crop)",
            "Crowd wave tracking swoop along front row (in pin-sharp portrait crop)",
            "Stage thrust flyover right over lead singer (in pin-sharp portrait crop)",
            "Symmetrical choir arch sweep (in pin-sharp portrait crop)",
            "Keynote entrance high boom down to podium (in pin-sharp portrait crop)",
            "Bouquet toss overhead arc tracking (in pin-sharp portrait crop)",
            "Finale pyro upward crane rise to rafters (in pin-sharp portrait crop)",
            "Sky-to-stage vertical descent (in pin-sharp portrait crop)",
            "Curved 180 yaw around center stage (in pin-sharp portrait crop)",
            "Descending spiral around lead performer (in pin-sharp portrait crop)",
            "Balcony to pit dramatic plunge (in pin-sharp portrait crop)",
            "Slow crane up reveal (with slow subtle handheld drift)",
            "Sweeping arc around subject (with slow subtle handheld drift)",
            "High to low dramatic descent (with slow subtle handheld drift)",
            "Float over the audience toward stage (with slow subtle handheld drift)",
            "Boom down to a close-up (with slow subtle handheld drift)",
        };

        private static readonly string[] OverheadShots = {
            "Bird's eye of stage layout",
            "Overhead of performer's instrument",
            "Top-down crowd pattern",
            "Straight down on the center mark",
            "Overhead tracking shot",
            "Top-down keyboard two-hand flurry",
            "Direct overhead drum kit geometric symmetry",
            "Overhead altar communion table arrangement",
            "Center stage circle spiral top-down",
            "Dance choreography formation geometric pattern",
            "Bird's eye of stage layout (with dynamic low-angle push)",
            "Overhead of performer's instrument (with dynamic low-angle push)",
            "Top-down crowd pattern (with dynamic low-angle push)",
            "Straight down on the center mark (with dynamic low-angle push)",
            "Overhead tracking shot (with dynamic low-angle push)",
            "Top-down keyboard two-hand flurry (with dynamic low-angle push)",
            "Direct overhead drum kit geometric symmetry (with dynamic low-angle push)",
            "Overhead altar communion table arrangement (with dynamic low-angle push)",
            "Center stage circle spiral top-down (with dynamic low-angle push)",
            "Dance choreography formation geometric pattern (with dynamic low-angle push)",
            "Bird's eye of stage layout (with golden ratio composition)",
            "Overhead of performer's instrument (with golden ratio composition)",
            "Top-down crowd pattern (with golden ratio composition)",
            "Straight down on the center mark (with golden ratio composition)",
            "Overhead tracking shot (with golden ratio composition)",
            "Top-down keyboard two-hand flurry (with golden ratio composition)",
            "Direct overhead drum kit geometric symmetry (with golden ratio composition)",
            "Overhead altar communion table arrangement (with golden ratio composition)",
            "Center stage circle spiral top-down (with golden ratio composition)",
            "Dance choreography formation geometric pattern (with golden ratio composition)",
            "Bird's eye of stage layout (with rim-light flare accent)",
            "Overhead of performer's instrument (with rim-light flare accent)",
            "Top-down crowd pattern (with rim-light flare accent)",
            "Straight down on the center mark (with rim-light flare accent)",
            "Overhead tracking shot (with rim-light flare accent)",
            "Top-down keyboard two-hand flurry (with rim-light flare accent)",
            "Direct overhead drum kit geometric symmetry (with rim-light flare accent)",
            "Overhead altar communion table arrangement (with rim-light flare accent)",
            "Center stage circle spiral top-down (with rim-light flare accent)",
            "Dance choreography formation geometric pattern (with rim-light flare accent)",
            "Bird's eye of stage layout (in pin-sharp portrait crop)",
            "Overhead of performer's instrument (in pin-sharp portrait crop)",
            "Top-down crowd pattern (in pin-sharp portrait crop)",
            "Straight down on the center mark (in pin-sharp portrait crop)",
            "Overhead tracking shot (in pin-sharp portrait crop)",
            "Top-down keyboard two-hand flurry (in pin-sharp portrait crop)",
            "Direct overhead drum kit geometric symmetry (in pin-sharp portrait crop)",
            "Overhead altar communion table arrangement (in pin-sharp portrait crop)",
            "Center stage circle spiral top-down (in pin-sharp portrait crop)",
            "Dance choreography formation geometric pattern (in pin-sharp portrait crop)",
            "Bird's eye of stage layout (with slow subtle handheld drift)",
            "Overhead of performer's instrument (with slow subtle handheld drift)",
            "Top-down crowd pattern (with slow subtle handheld drift)",
            "Straight down on the center mark (with slow subtle handheld drift)",
            "Overhead tracking shot (with slow subtle handheld drift)",
            "Top-down keyboard two-hand flurry (with slow subtle handheld drift)",
            "Direct overhead drum kit geometric symmetry (with slow subtle handheld drift)",
            "Overhead altar communion table arrangement (with slow subtle handheld drift)",
            "Center stage circle spiral top-down (with slow subtle handheld drift)",
            "Dance choreography formation geometric pattern (with slow subtle handheld drift)",
            "Bird's eye of stage layout (with high contrast backlight)",
            "Overhead of performer's instrument (with high contrast backlight)",
            "Top-down crowd pattern (with high contrast backlight)",
            "Straight down on the center mark (with high contrast backlight)",
            "Overhead tracking shot (with high contrast backlight)",
            "Top-down keyboard two-hand flurry (with high contrast backlight)",
            "Direct overhead drum kit geometric symmetry (with high contrast backlight)",
            "Overhead altar communion table arrangement (with high contrast backlight)",
            "Center stage circle spiral top-down (with high contrast backlight)",
            "Dance choreography formation geometric pattern (with high contrast backlight)",
            "Bird's eye of stage layout (framed with generous lead room)",
            "Overhead of performer's instrument (framed with generous lead room)",
            "Top-down crowd pattern (framed with generous lead room)",
            "Straight down on the center mark (framed with generous lead room)",
            "Overhead tracking shot (framed with generous lead room)",
            "Top-down keyboard two-hand flurry (framed with generous lead room)",
            "Direct overhead drum kit geometric symmetry (framed with generous lead room)",
            "Overhead altar communion table arrangement (framed with generous lead room)",
            "Center stage circle spiral top-down (framed with generous lead room)",
            "Dance choreography formation geometric pattern (framed with generous lead room)",
            "Bird's eye of stage layout (holding rock-steady horizon)",
            "Overhead of performer's instrument (holding rock-steady horizon)",
            "Top-down crowd pattern (holding rock-steady horizon)",
            "Straight down on the center mark (holding rock-steady horizon)",
            "Overhead tracking shot (holding rock-steady horizon)",
            "Top-down keyboard two-hand flurry (holding rock-steady horizon)",
            "Direct overhead drum kit geometric symmetry (holding rock-steady horizon)",
            "Overhead altar communion table arrangement (holding rock-steady horizon)",
            "Center stage circle spiral top-down (holding rock-steady horizon)",
            "Dance choreography formation geometric pattern (holding rock-steady horizon)",
            "Bird's eye of stage layout (with dramatic negative space)",
            "Overhead of performer's instrument (with dramatic negative space)",
            "Top-down crowd pattern (with dramatic negative space)",
            "Straight down on the center mark (with dramatic negative space)",
            "Overhead tracking shot (with dramatic negative space)",
            "Top-down keyboard two-hand flurry (with dramatic negative space)",
            "Direct overhead drum kit geometric symmetry (with dramatic negative space)",
            "Overhead altar communion table arrangement (with dramatic negative space)",
            "Center stage circle spiral top-down (with dramatic negative space)",
            "Dance choreography formation geometric pattern (with dramatic negative space)",
            "Bird's eye of stage layout (accenting foreground depth)",
            "Overhead of performer's instrument (accenting foreground depth)",
            "Top-down crowd pattern (accenting foreground depth)",
            "Straight down on the center mark (accenting foreground depth)",
            "Overhead tracking shot (accenting foreground depth)",
        };

        private static readonly string[] BRollShots = {
            "Detail shot of branding/logos",
            "Abstract lighting flare shot",
            "Slow pan across equipment/instruments",
            "Architectural detail of the venue",
            "Time-lapse style static holding shot",
            "Anamorphic horizontal lens flare",
            "Vintage tube amplifier orange glow",
            "Soundboard faders moving in automation",
            "Cable snake texture and stage gaffer tape",
            "Stage technician cueing headset silhouette",
            "Detail shot of branding/logos (with dynamic low-angle push)",
            "Abstract lighting flare shot (with dynamic low-angle push)",
            "Slow pan across equipment/instruments (with dynamic low-angle push)",
            "Architectural detail of the venue (with dynamic low-angle push)",
            "Time-lapse style static holding shot (with dynamic low-angle push)",
            "Anamorphic horizontal lens flare (with dynamic low-angle push)",
            "Vintage tube amplifier orange glow (with dynamic low-angle push)",
            "Soundboard faders moving in automation (with dynamic low-angle push)",
            "Cable snake texture and stage gaffer tape (with dynamic low-angle push)",
            "Stage technician cueing headset silhouette (with dynamic low-angle push)",
            "Detail shot of branding/logos (with golden ratio composition)",
            "Abstract lighting flare shot (with golden ratio composition)",
            "Slow pan across equipment/instruments (with golden ratio composition)",
            "Architectural detail of the venue (with golden ratio composition)",
            "Time-lapse style static holding shot (with golden ratio composition)",
            "Anamorphic horizontal lens flare (with golden ratio composition)",
            "Vintage tube amplifier orange glow (with golden ratio composition)",
            "Soundboard faders moving in automation (with golden ratio composition)",
            "Cable snake texture and stage gaffer tape (with golden ratio composition)",
            "Stage technician cueing headset silhouette (with golden ratio composition)",
            "Detail shot of branding/logos (with rim-light flare accent)",
            "Abstract lighting flare shot (with rim-light flare accent)",
            "Slow pan across equipment/instruments (with rim-light flare accent)",
            "Architectural detail of the venue (with rim-light flare accent)",
            "Time-lapse style static holding shot (with rim-light flare accent)",
            "Anamorphic horizontal lens flare (with rim-light flare accent)",
            "Vintage tube amplifier orange glow (with rim-light flare accent)",
            "Soundboard faders moving in automation (with rim-light flare accent)",
            "Cable snake texture and stage gaffer tape (with rim-light flare accent)",
            "Stage technician cueing headset silhouette (with rim-light flare accent)",
            "Detail shot of branding/logos (in pin-sharp portrait crop)",
            "Abstract lighting flare shot (in pin-sharp portrait crop)",
            "Slow pan across equipment/instruments (in pin-sharp portrait crop)",
            "Architectural detail of the venue (in pin-sharp portrait crop)",
            "Time-lapse style static holding shot (in pin-sharp portrait crop)",
            "Anamorphic horizontal lens flare (in pin-sharp portrait crop)",
            "Vintage tube amplifier orange glow (in pin-sharp portrait crop)",
            "Soundboard faders moving in automation (in pin-sharp portrait crop)",
            "Cable snake texture and stage gaffer tape (in pin-sharp portrait crop)",
            "Stage technician cueing headset silhouette (in pin-sharp portrait crop)",
            "Detail shot of branding/logos (with slow subtle handheld drift)",
            "Abstract lighting flare shot (with slow subtle handheld drift)",
            "Slow pan across equipment/instruments (with slow subtle handheld drift)",
            "Architectural detail of the venue (with slow subtle handheld drift)",
            "Time-lapse style static holding shot (with slow subtle handheld drift)",
            "Anamorphic horizontal lens flare (with slow subtle handheld drift)",
            "Vintage tube amplifier orange glow (with slow subtle handheld drift)",
            "Soundboard faders moving in automation (with slow subtle handheld drift)",
            "Cable snake texture and stage gaffer tape (with slow subtle handheld drift)",
            "Stage technician cueing headset silhouette (with slow subtle handheld drift)",
            "Detail shot of branding/logos (with high contrast backlight)",
            "Abstract lighting flare shot (with high contrast backlight)",
            "Slow pan across equipment/instruments (with high contrast backlight)",
            "Architectural detail of the venue (with high contrast backlight)",
            "Time-lapse style static holding shot (with high contrast backlight)",
            "Anamorphic horizontal lens flare (with high contrast backlight)",
            "Vintage tube amplifier orange glow (with high contrast backlight)",
            "Soundboard faders moving in automation (with high contrast backlight)",
            "Cable snake texture and stage gaffer tape (with high contrast backlight)",
            "Stage technician cueing headset silhouette (with high contrast backlight)",
            "Detail shot of branding/logos (framed with generous lead room)",
            "Abstract lighting flare shot (framed with generous lead room)",
            "Slow pan across equipment/instruments (framed with generous lead room)",
            "Architectural detail of the venue (framed with generous lead room)",
            "Time-lapse style static holding shot (framed with generous lead room)",
            "Anamorphic horizontal lens flare (framed with generous lead room)",
            "Vintage tube amplifier orange glow (framed with generous lead room)",
            "Soundboard faders moving in automation (framed with generous lead room)",
            "Cable snake texture and stage gaffer tape (framed with generous lead room)",
            "Stage technician cueing headset silhouette (framed with generous lead room)",
            "Detail shot of branding/logos (holding rock-steady horizon)",
            "Abstract lighting flare shot (holding rock-steady horizon)",
            "Slow pan across equipment/instruments (holding rock-steady horizon)",
            "Architectural detail of the venue (holding rock-steady horizon)",
            "Time-lapse style static holding shot (holding rock-steady horizon)",
            "Anamorphic horizontal lens flare (holding rock-steady horizon)",
            "Vintage tube amplifier orange glow (holding rock-steady horizon)",
            "Soundboard faders moving in automation (holding rock-steady horizon)",
            "Cable snake texture and stage gaffer tape (holding rock-steady horizon)",
            "Stage technician cueing headset silhouette (holding rock-steady horizon)",
            "Detail shot of branding/logos (with dramatic negative space)",
            "Abstract lighting flare shot (with dramatic negative space)",
            "Slow pan across equipment/instruments (with dramatic negative space)",
            "Architectural detail of the venue (with dramatic negative space)",
            "Time-lapse style static holding shot (with dramatic negative space)",
            "Anamorphic horizontal lens flare (with dramatic negative space)",
            "Vintage tube amplifier orange glow (with dramatic negative space)",
            "Soundboard faders moving in automation (with dramatic negative space)",
            "Cable snake texture and stage gaffer tape (with dramatic negative space)",
            "Stage technician cueing headset silhouette (with dramatic negative space)",
            "Detail shot of branding/logos (accenting foreground depth)",
            "Abstract lighting flare shot (accenting foreground depth)",
            "Slow pan across equipment/instruments (accenting foreground depth)",
            "Architectural detail of the venue (accenting foreground depth)",
            "Time-lapse style static holding shot (accenting foreground depth)",
        };

        public static ShotSuggestion GenerateShotForRole(CameraRoleMetadata roleInfo, int cameraId)
        {
            string title;
            string description;
            string roleStr = roleInfo?.Role ?? "Unknown";
            string roleLower = roleStr.ToLowerInvariant();

            string[] shotPool;

            if (roleLower.Contains("roving") && roleLower.Contains("stage"))
            {
                shotPool = RovingStageShots;
            }
            else if (roleLower.Contains("roving") && roleLower.Contains("audience"))
            {
                shotPool = RovingAudienceShots;
            }
            else if (roleLower.Contains("crane") || roleLower.Contains("jib"))
            {
                shotPool = CraneJibShots;
            }
            else if (roleLower.Contains("overhead"))
            {
                shotPool = OverheadShots;
            }
            else if (roleLower.Contains("b-roll"))
            {
                shotPool = BRollShots;
            }
            else if (roleLower.Contains("wide"))
            {
                shotPool = WideShots;
            }
            else if (roleLower.Contains("close-up") || roleLower.Contains("close"))
            {
                shotPool = CloseUpShots;
            }
            else
            {
                if (roleInfo?.SubjectArea == "audience")
                {
                    shotPool = RovingAudienceShots;
                }
                else if (roleInfo?.DefaultFraming == "wide")
                {
                    shotPool = WideShots;
                }
                else if (roleInfo?.DefaultFraming == "close")
                {
                    shotPool = CloseUpShots;
                }
                else
                {
                    shotPool = GenericShots;
                }
            }

            title = PickRandomUnique(cameraId, shotPool);
            description = $"Suggested based on your role: {roleStr}";

            return new ShotSuggestion(
                Id: Guid.NewGuid().ToString(),
                Title: title,
                Description: description,
                Category: "AI Director",
                DurationSeconds: 15
            )
            {
                IsAiGenerated = true
            };
        }

        private static string PickRandomUnique(int cameraId, string[] pool)
        {
            if (!RecentShots.ContainsKey(cameraId))
            {
                RecentShots[cameraId] = new Queue<string>();
            }

            var history = RecentShots[cameraId];
            
            if (pool.Length <= history.Count)
            {
                return pool[Rnd.Next(pool.Length)];
            }

            string pick;
            int attempts = 0;
            do
            {
                pick = pool[Rnd.Next(pool.Length)];
                attempts++;
            } while (history.Contains(pick) && attempts < 20);

            history.Enqueue(pick);
            if (history.Count > HistorySize)
            {
                history.Dequeue();
            }

            return pick;
        }
    }
}
